FROM nextcloud:fpm-alpine

RUN set -x \
    && apk update\
    && apk add --no-cache nginx sudo

COPY data/nginx/sites-enabled/default /etc/nginx/sites-enabled/default
COPY data/nginx/nginx.conf /etc/nginx/nginx.conf
COPY data/*.sh /

RUN set -x && apk add --no-cache supervisor \
    && chmod 755 /*.sh \
    && mkdir /var/run/php && chown -R 82:82 /var/run/php

COPY data/supervisord/supervisord.conf /etc/supervisor/supervisord.conf
COPY data/supervisord/conf.d/ /etc/supervisor/conf.d/
COPY data/php/php-fpm.d/www.conf /usr/local/etc/php-fpm.d/www.conf
COPY data/php/php-fpm.d/zz-docker.conf /usr/local/etc/php-fpm.d/zz-docker.conf

CMD ["/bin/sh", "/start.sh"]
